FROM soar97/triton-cosyvoice:25.06

RUN pip install --no-cache-dir cython && \
    pip install --no-cache-dir --no-build-isolation --no-deps matcha-tts && \
    pip install --no-cache-dir "s3tokenizer>=0.3" x-transformers && \
    pip install --no-cache-dir --no-deps \
      "git+https://github.com/ToolsAiforia/FastCosyVoice@v0.0.1"

# WORKDIR /workspace gets overwritten by runpod
WORKDIR /workdir

ADD ./Fun-CosyVoice3-0.5B-2512 /workdir/Fun-CosyVoice3-0.5B-2512
ADD ./cosyvoice3_llm /workdir/cosyvoice3_llm
ADD ./cosyvoice3_trt_engines /workdir/cosyvoice3_trt_engines
ADD ./model_repo_cosyvoice3 /model_repo

COPY entrypoint_cosyvoice3.sh /workdir/entrypoint.sh
COPY scripts/fill_template.py /workdir/scripts/fill_template.py
RUN chmod +x /workdir/entrypoint.sh

EXPOSE 8000 8001 8002
ENTRYPOINT ["/workdir/entrypoint.sh"]
